# Generated by Django 6.0.3 on 2026-03-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_returnrequest_returnitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="shipping_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
