# Generated by Django 4.2.7 on 2026-03-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                ],
                default="published",
                max_length=20,
            ),
        ),
    ]
