# Generated by Django 6.0.3 on 2026-03-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_sellerprofile_sender_address_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="admin_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="last_login_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
